language: python
python:
  - "3.7"
env:
  - DJANGO_VERSION=2.2.1

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source='.' OVTS-Server/manage.py test deviceApp
after_success:
  - coveralls
