# Generated by Django 2.2.4 on 2019-09-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecentercommandsmodel',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='devicerawdatamodel',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devicecentercommandsmodel',
            name='device_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.DeviceInfo'),
            preserve_default=False,
        ),
    ]
