# Generated by Django 2.2.4 on 2019-09-10 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0002_auto_20190910_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_file', models.FileField(upload_to='DeviceReport')),
                ('device_datas', models.ManyToManyField(to='deviceApp.DeviceDataModel')),
                ('device_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceApp.DeviceInfo')),
            ],
        ),
    ]
