# Generated by Django 2.2.4 on 2019-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0005_auto_20190910_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecentercommandsmodel',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='devicerawdatamodel',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='devicereportmodel',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
