# Generated by Django 2.2.4 on 2019-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0006_auto_20190910_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerawdatamodel',
            name='b64_data',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterUniqueTogether(
            name='devicerawdatamodel',
            unique_together={('device_object', 'b64_data')},
        ),
    ]
