# Generated by Django 2.2.4 on 2019-09-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0007_auto_20190910_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imumodel',
            unique_together={('ax', 'ay', 'az')},
        ),
    ]
