# Generated by Django 2.2.4 on 2019-09-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0008_auto_20190910_2039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imumodel',
            unique_together=set(),
        ),
    ]
