# Generated by Django 2.2.4 on 2019-09-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0009_auto_20190910_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDataReportModel',
            fields=[
                ('raw_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deviceApp.DeviceRawDataModel')),
                ('time', models.IntegerField()),
                ('relay', models.IntegerField(blank=True, null=True)),
                ('input_sensor', models.IntegerField(blank=True, null=True)),
                ('sim_balance', models.IntegerField(blank=True, null=True)),
                ('signal_quality', models.IntegerField(blank=True, null=True)),
                ('battery_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.BatteryModel')),
                ('center_params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.CenterParamsModel')),
                ('custom_field', models.ManyToManyField(blank=True, to='deviceApp.CustomFieldModel')),
                ('device_params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.DeviceParamsModel')),
                ('gps_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.GPSModel')),
                ('imu_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceApp.IMUModel')),
            ],
        ),
        migrations.AlterField(
            model_name='devicereportmodel',
            name='device_datas',
            field=models.ManyToManyField(to='deviceApp.DeviceDataReportModel'),
        ),
    ]
