# Generated by Django 2.2.4 on 2019-09-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0010_auto_20190911_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerawdatamodel',
            name='is_valid',
        ),
    ]
